apiVersion: v1
kind: Service
metadata:
  name: application-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # Specify that the load balancer should be private  # Specify that the load balancer should be internal/private
spec:
  type: LoadBalancer
  selector:
    app: app-name
  ports:
  - port: 80
    targetPort: 8080 #application port
    name: port1
  - port: 1099       # port for connecting to the JFR monitoring
    targetPort: 1099
    name: port2
